### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by qn2060** [casdoor/casdoor-python-sdk#47]
![image](https://github.com/casdoor/casdoor-python-sdk/assets/15309040/d58e09a6-27ab-4b1c-b6f6-c186d7e64b69)

docker python:3.8

pip install casdoor

from casdoor import CasdoorSDK

**Comment by hsluoyz** [comment]
@qn2060 which version of casdoor-python-sdk do you use?

**Comment by qn2060** [comment]
@hsluoyz  the latest 1.12.0 ,  I changed to 1.11.0  and working well.

**Comment by hsluoyz** [comment]
@qn2060 I have tested the latest casdoor-python-sdk `v1.13.0` with the Python example: https://github.com/casdoor/casdoor-python-vue-sdk-example/commit/b2acf6ac9901857a8062a9c59889f09b83b43b44

It works well.

Python 3.9.13

**Comment by qn2060** [comment]
thanks
