### ISSUE TITLE
can't getting token on username and password basis.

### ISSUE THREAD

**Issue by nihalgurjar47** [casdoor/casdoor-python-sdk#48]
I read this document of yours, located at https://github.com/casdoor/casdoor-python-sdk. In this document, you have implemented a way to obtain a token based on a username and password.
However, I am unable to obtain the token.
I am encountering an error. Please refer to the screenshot below for further details.
![Screenshot from 2023-07-04 18-34-14](https://github.com/casdoor/casdoor/assets/104414738/670ad094-abad-431f-803b-18b1f6289012)

**Comment by hsluoyz** [comment]
Answered here: https://github.com/casdoor/casdoor/issues/2038

**Comment by nihalgurjar47** [comment]
Thanks for update its work for me.



[cid:af805498-a279-4d23-8582-00955bc59667]Hello World!

Nihal Gurjar
Software Engineer

Cell:  8770316617
www.47billion.com<http://www.47billion.com>
Read: Blog<https://47billion.com/blog>  |  Follow us: Linkedin<https://www.linkedin.com/company/47billion>  |  Twitter<https://twitter.com/47Billion>  |  FB<https://www.facebook.com/47Billion>

________________________________
