### ISSUE TITLE
The token is not yet valid (iat)  ERROR in function parse_jwt_token(access_token)

### ISSUE THREAD

**Issue by qn2060** [casdoor/casdoor-python-sdk#58]
![image](https://github.com/casdoor/casdoor-python-sdk/assets/15309040/97295ce4-4996-4b29-8f7b-889f1e4b4880)
casdoor==1.13.1
python  3.7.9

**Comment by hsluoyz** [comment]
@qn2060 use Casdoor latest version, v1.382.0 for now: https://github.com/casdoor/casdoor/releases/tag/v1.382.0
