### ISSUE TITLE
The token is not yet valid (iat) ERROR in function parse_jwt_token(access_token) 

### ISSUE THREAD

**Issue by qn2060** [casdoor/casdoor-python-sdk#63]
![image](https://github.com/casdoor/casdoor-python-sdk/assets/15309040/0c726d24-6a2d-459c-bad7-7b45c975609f)

python sdk 1.15.0  casdoor v1.382.0   python  3.10 & 3.7

**Comment by brownfoxsir** [comment]
@qn2060    Your token is invalid

**Comment by hsluoyz** [comment]
@qn2060 try this example: https://github.com/casdoor/casdoor-python-vue-sdk-example , I tested it and it worked

**Comment by hsluoyz** [comment]
Closed as invalid
