### ISSUE TITLE
Upgrade the Casdoor-Python-SDK to latest

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-python-sdk#8]
The code in this repo is very old. We need to port all changes from Go: https://github.com/casdoor/casdoor-nodejs-sdk/issues/7

**Comment by hsluoyz** [comment]
@Abingcbc @Nekotoxin

**Comment by ffyuanda** [comment]
Could we possibly set up a GitHub Action service so the tests can run against a Casdoor instance
in the VM?

**Comment by hsluoyz** [comment]
> OK, then I'm claiming this issue, will launch a few patches tomorrow.

@ffyuanda any update?

**Comment by ffyuanda** [comment]
WIP

**Comment by ffyuanda** [comment]
Barely got enough time these days, now transferring the work to @Steve0x2a , thanks.

**Comment by hsluoyz** [comment]
Hi @epis2048 I saw you have updated the SDK here: https://www.epis2048.net/2022/casdoor-fuck/index.html , are you willing to contribute it back to the community?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor-python-sdk/pull/15
