### ISSUE TITLE
[Bug]missing depenencies in package

### ISSUE THREAD

**Issue by anyidea** [casdoor/casdoor-python-sdk#80]
`aiohttp` and `PyJWT` are required in latest version 1.20, please make them package depedencies.

**Comment by hsluoyz** [comment]
@anyidea aren't they already there?

https://github.com/casdoor/casdoor-python-sdk/blob/f9b8204655c4a1a9b4c635a5f5141ed3b5b938f3/requirements.txt#L1-L6
