### ISSUE TITLE
Set up the GitHub Actions CI service

### ISSUE THREAD

**Issue by ffyuanda** [casdoor/casdoor-python-sdk#9]
For now, the tests are hard-coded and no longer valid.
If we set up a Casdoor instance in CI service, then we 
can run the tests in the environment against that
instance.

**Comment by hsluoyz** [comment]
@ffyuanda you can use the demo site: https://door.casdoor.com/ even in CI. It will be always up.

**Comment by Steve0x2a** [comment]
> @ffyuanda you can use the demo site: https://door.casdoor.com/ even in CI. It will be always up.

Casdoor code can only be used once now, so it is possible that the existing test will need to be modified.

**Comment by hsluoyz** [comment]
@Steve0x2a I think the current problem is that the Actions CI doesn't run at all, not the run causes failure. We need to figure out how to make it run first.

**Comment by hsluoyz** [comment]
See the CI icon: https://github.com/casbin/pycasbin/commits/master

![image](https://user-images.githubusercontent.com/3787410/157707678-646c747e-cbb1-4e9d-975f-76ddaeecee58.png)

But we this repo doesn't have it: https://github.com/casdoor/casdoor-python-sdk/commits/master

![image](https://user-images.githubusercontent.com/3787410/157707789-5ca50577-7e6d-4702-8c64-e9d771800e36.png)
